# Generated by Django 3.2.7 on 2021-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsowit', '0002_mapsowit_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsowit',
            name='image_url_plot',
            field=models.TextField(default=''),
        ),
    ]
